### ISSUE TITLE
Support file flag

### ISSUE THREAD

**Issue by logileifs** [logileifs/shellson#4]
instead of only accepting input from stdin shellson should be able to read json from file itself

**Comment by gsailer** [comment]
Hi Logi,

I like the idea of this tool and would like to implement the file read feature.
What do you think about the introduction of argparse at this point to accomplish a nice looking help and the necessary flag for the file?

-Gabriel

**Comment by logileifs** [comment]
done https://github.com/logileifs/shellson/pull/5
